# Generated by Django 2.2.10 on 2020-05-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20200515_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default='5', max_length=2),
        ),
        migrations.AlterField(
            model_name='rating',
            name='site_or_quiz',
            field=models.IntegerField(choices=[('QUIZ', 'Quiz'), ('SITE', 'Site')], default='QUIZ', max_length=5),
        ),
    ]
