# Generated by Django 3.0.3 on 2020-05-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_auto_20200516_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comments',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='site_or_quiz',
            field=models.CharField(choices=[('QUIZ', 'Quiz'), ('SITE', 'Site')], default='Quiz', max_length=5),
        ),
    ]
