# Generated by Django 2.2.10 on 2020-05-15 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200515_1310'),
        ('score', '0002_auto_20200515_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userscore',
            name='user_id',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile', verbose_name='user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userscore',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile', verbose_name='user'),
            preserve_default=False,
        ),
    ]
