# Generated by Django 2.2.10 on 2020-05-16 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_quiz_no_of_question_to_display'),
        ('score', '0003_auto_20200515_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='quiz_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question.Quiz', verbose_name='quiz'),
            preserve_default=False,
        ),
    ]
