# Generated by Django 2.2.10 on 2020-05-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_useranswer_quiz_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscore',
            name='score',
            field=models.FloatField(),
        ),
    ]
