# Generated by Django 3.0.3 on 2020-05-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0005_auto_20200516_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='is_pass',
            field=models.BooleanField(default=False),
        ),
    ]
