# Generated by Django 3.0.3 on 2020-05-30 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_userprofile_roll_no'),
        ('question', '0014_auto_20200530_1959'),
        ('score', '0006_userscore_is_pass'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userscore',
            unique_together={('user', 'quiz_id')},
        ),
    ]
