# Generated by Django 2.1.15 on 2020-06-05 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_text', models.CharField(blank=True, max_length=500, null=True)),
                ('answer_image', models.ImageField(blank=True, null=True, upload_to='quiz/staticfiles')),
                ('is_correct_answer', models.CharField(choices=[('TRUE', 'True'), ('FALSE', 'False')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Answers',
                'db_table': 'answer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Domains',
                'db_table': 'domain',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='quiz/staticfiles')),
                ('mark', models.IntegerField()),
                ('question_type', models.CharField(choices=[('SINGLECHOICE', 'SingleChoice'), ('MULTIPLECHOICE', 'MultipleChoice'), ('TEXT', 'Text')], max_length=20)),
                ('no_of_answers', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Questions',
                'db_table': 'question',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('no_of_questions', models.IntegerField()),
                ('no_of_question_to_display', models.IntegerField()),
                ('pass_mark', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('time_in_minutes', models.IntegerField()),
                ('quiz_start_time', models.DateTimeField(blank=True, null=True)),
                ('quiz_end_time', models.DateTimeField(blank=True, null=True)),
                ('quiz_image', models.ImageField(blank=True, null=True, upload_to='quiz/staticfiles')),
                ('hardness', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCE', 'Advance')], default='BEGINNER', max_length=20)),
                ('domain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Domain', verbose_name='domain')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
                'db_table': 'quiz',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Quiz', verbose_name='quiz'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question', verbose_name='question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Quiz', verbose_name='quiz'),
        ),
    ]
