# Generated by Django 2.2.10 on 2020-05-14 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Domains',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('no_of_questions', models.IntegerField()),
                ('pass_mark', models.IntegerField()),
                ('quiz_image', models.BinaryField(blank=True)),
                ('hardness', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCE', 'Advance')], default='BEGINNER', max_length=10)),
                ('domain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Domain', verbose_name='domain')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=5000)),
                ('question_image', models.BinaryField(blank=True)),
                ('mark', models.IntegerField()),
                ('quiz_type', models.CharField(choices=[('SINGLECHOICE', 'SingleChoice'), ('MULTIPLECHOICE', 'MultipleChoice')], max_length=10)),
                ('no_of_answers', models.IntegerField()),
                ('correct_answer_id', models.IntegerField()),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Quiz', verbose_name='quiz')),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_text', models.CharField(max_length=500)),
                ('answer_image', models.BinaryField(blank=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question', verbose_name='question')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Quiz', verbose_name='quiz')),
            ],
            options={
                'verbose_name_plural': 'Answers',
            },
        ),
    ]
