# Generated by Django 2.2.10 on 2020-05-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz_type',
            field=models.CharField(choices=[('SINGLECHOICE', 'SingleChoice'), ('MULTIPLECHOICE', 'MultipleChoice')], max_length=20),
        ),
    ]
