# Generated by Django 2.2.10 on 2020-05-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20200514_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_in_minutes',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_marks',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
