# Generated by Django 2.2.10 on 2020-05-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20200515_0701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'managed': True, 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'managed': True, 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelTable(
            name='answer',
            table='answer',
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
    ]
