# Generated by Django 2.2.10 on 2020-05-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20200515_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_correct_answer',
            field=models.CharField(choices=[('TRUE', 'True'), ('FALSE', 'False')], default=False, max_length=10),
            preserve_default=False,
        ),
    ]
