# Generated by Django 2.2.10 on 2020-05-15 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20200515_0722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quiz_type',
            new_name='question_type',
        ),
    ]
