# Generated by Django 2.2.10 on 2020-05-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_auto_20200516_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_correct_answer',
            field=models.CharField(choices=[('TRUE', 'True'), ('FALSE', 'False')], max_length=10),
        ),
    ]
