# Generated by Django 3.0.3 on 2020-05-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_auto_20200516_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_image',
            field=models.ImageField(upload_to='quiz/staticfiles'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(upload_to='quiz/staticfiles'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='hardness',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCE', 'Advance')], default='BEGINNER', max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_image',
            field=models.ImageField(upload_to='quiz/staticfiles'),
        ),
    ]
