# Generated by Django 2.2.10 on 2020-05-14 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Section',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Year',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Department', verbose_name='department')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Section', verbose_name='section')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Year', verbose_name='year')),
            ],
            options={
                'verbose_name_plural': 'User',
            },
        ),
    ]
