# Generated by Django 2.2.10 on 2020-05-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='year',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
