# Generated by Django 2.2.10 on 2020-05-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200514_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'managed': True, 'verbose_name_plural': 'Department'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'managed': True, 'verbose_name_plural': 'Section'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'verbose_name_plural': 'User'},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'managed': True, 'verbose_name_plural': 'Year'},
        ),
        migrations.AddField(
            model_name='user',
            name='roll_no',
            field=models.CharField(default='16bcs071', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='section',
            table='section',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='year',
            table='year',
        ),
    ]
