# Generated by Django 2.2.10 on 2020-05-15 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20200515_1310'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('score', '0002_auto_20200515_1310'),
        ('user', '0003_auto_20200515_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=15)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Department', verbose_name='department')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Section', verbose_name='section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Year', verbose_name='year')),
            ],
            options={
                'verbose_name_plural': 'UserProfile',
                'db_table': 'UserProfile',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
