# Generated by Django 2.2.10 on 2020-05-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200515_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='roll_no',
        ),
    ]
